### ISSUE TITLE
ACHA agent?

### ISSUE THREAD

**Issue by chiangqiqi** [deepmind/hanabi-learning-environment#13]
Hi, I'm just curious that why ACHA agent is not included in this repo?

**Comment by NeilBurch** [comment]
Thanks for the question. In this case, it would have been a significant effort to write a new version from scratch that was designed for public release.

**Comment by chiangqiqi** [comment]
Thanks for your reply, looking forward to see that 👍

**Comment by aronsar** [comment]
Hello, are there any plans to release the ACHA agent in the near future?

**Comment by NeilBurch** [comment]
There are no such plans.  It would require writing a new version from scratch, and would be a significant effort, like the Dopamine code release.
