### ISSUE TITLE
Question: Why no observation stacking?

### ISSUE THREAD

**Issue by carlbalmer** [deepmind/hanabi-learning-environment#26]
In the Paper you state that you did not use any observation stacking outside the previous action by the player.

What is the reasoning for this? Did you try out configurations with stacking and they did not perform well?

Another possibility would have been to include the other players action since the current players last action. Was something like this considered?

**Comment by mgbellemare** [comment]
Yes, observation stacking didn't seem to provide any immediate benefit. It's possible that recent observations are not more useful than the most recent one.

**Comment by carlbalmer** [comment]
Ok. Thanks a lot!

Looking at the code it seems as you are only recording (and stacking) the observations for active players. Therefore the agent can not directly observe the moves of the other players (like walking out of the room after your move and only coming back on your next turn). Of course the game state reflects the moves of the other players, but there is some ambiguity.

Maybe this is the reason observation stacking was not that useful.
